version: '3.8'

services:
  # ========================================
  # EXISTING CONTAINERS (Pull from Registry)
  # ========================================
  
  # WTSI Samtools - BCFtools, SAMtools, HTSlib, tabix
  bcftools:
    image: ghcr.io/wtsi-npg/samtools:latest
    volumes:
      - ./data:/data
      - ./input:/input
      - ./output:/output
    working_dir: /data
    profiles: ["existing", "all"]

  # BioContainers VCFtools  
  vcftools:
    image: quay.io/biocontainers/vcftools:latest
    volumes:
      - ./data:/data
      - ./input:/input
      - ./output:/output
    working_dir: /data
    profiles: ["existing", "all"]

  # Python environment for analysis
  python-analysis:
    image: python:3.11-slim
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    working_dir: /data
    command: python --version
    profiles: ["existing", "all"]

  # R environment for statistical analysis
  r-analysis:
    image: bioconductor/bioconductor_docker:latest
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    working_dir: /data
    command: R --version
    profiles: ["existing", "all"]

  # ========================================
  # CUSTOM CONTAINERS (Build Locally)
  # ========================================

  # Eagle phasing
  eagle-phasing:
    build:
      context: ./eagle-phasing
      dockerfile: Dockerfile
    image: ghcr.io/afrigen-d/eagle-phasing:latest
    volumes:
      - ./data:/data
      - ./input:/input
      - ./output:/output
    working_dir: /data
    profiles: ["custom", "all"]

  # Minimac4 imputation
  minimac4:
    build:
      context: ./minimac4
      dockerfile: Dockerfile
    image: ghcr.io/afrigen-d/minimac4:latest
    volumes:
      - ./data:/data
      - ./input:/input
      - ./output:/output
    working_dir: /data
    profiles: ["custom", "all"]

  # PLINK 2.0
  plink2:
    build:
      context: ./plink2
      dockerfile: Dockerfile
    image: ghcr.io/afrigen-d/plink2:latest
    volumes:
      - ./data:/data
      - ./input:/input
      - ./output:/output
    working_dir: /data
    profiles: ["custom", "all"]

  # All-in-one container (includes everything)
  all-in-one:
    build:
      context: ./all-in-one
      dockerfile: Dockerfile
    image: ghcr.io/afrigen-d/genotype-imputation:latest
    volumes:
      - ./data:/data
      - ./input:/input
      - ./output:/output
      - ./scripts:/scripts
    working_dir: /data
    profiles: ["custom", "all"]

# Named volumes for persistent data
volumes:
  data:
  input:
  output:

# Networks
networks:
  default:
    name: genotype-imputation 