name: Build Eagle + VCF Processing Container

on:
  push:
    branches: [ main, master ]
    paths:
      - 'containers/eagle-vcf-processing/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'containers/eagle-vcf-processing/**'
  workflow_dispatch:
    inputs:
      push_to_registry:
        description: 'Push to Docker Hub (requires secrets)'
        required: true
        default: false
        type: boolean
      build_only:
        description: 'Build only (no push)'
        required: true
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      if: github.event_name == 'workflow_dispatch' && inputs.push_to_registry == 'true' && inputs.build_only == 'false'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build Eagle + VCF Processing container
      uses: docker/build-push-action@v5
      with:
        context: ./containers/eagle-vcf-processing
        push: ${{ github.event_name == 'workflow_dispatch' && inputs.push_to_registry == 'true' && inputs.build_only == 'false' }}
        tags: |
          mamana/eagle-vcf-processing:eagle-2.4.1
          mamana/eagle-vcf-processing:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64
        
    - name: Test container (automatic build)
      if: github.event_name == 'push' || github.event_name == 'pull_request'
      run: |
        echo "Testing automatically built container..."
        docker run --rm mamana/eagle-vcf-processing:eagle-2.4.1 eagle --version
        docker run --rm mamana/eagle-vcf-processing:eagle-2.4.1 tabix --version
        docker run --rm mamana/eagle-vcf-processing:eagle-2.4.1 bcftools --version
        docker run --rm mamana/eagle-vcf-processing:eagle-2.4.1 eagle_vcf_tools_info
        
    - name: Test container (local build)
      if: github.event_name == 'workflow_dispatch' && inputs.build_only == 'true'
      run: |
        echo "Testing locally built container..."
        docker run --rm mamana/eagle-vcf-processing:eagle-2.4.1 eagle --version
        docker run --rm mamana/eagle-vcf-processing:eagle-2.4.1 tabix --version
        docker run --rm mamana/eagle-vcf-processing:eagle-2.4.1 bcftools --version
        docker run --rm mamana/eagle-vcf-processing:eagle-2.4.1 eagle_vcf_tools_info
        
    - name: Test container (pushed build)
      if: github.event_name == 'workflow_dispatch' && inputs.push_to_registry == 'true' && inputs.build_only == 'false'
      run: |
        echo "Testing pushed container..."
        docker run --rm mamana/eagle-vcf-processing:eagle-2.4.1 eagle --version
        docker run --rm mamana/eagle-vcf-processing:eagle-2.4.1 tabix --version
        docker run --rm mamana/eagle-vcf-processing:eagle-2.4.1 bcftools --version
        docker run --rm mamana/eagle-vcf-processing:eagle-2.4.1 eagle_vcf_tools_info
        
    - name: Build summary
      run: |
        echo "=== Eagle + VCF Processing Container Build Summary ==="
        echo "Event: ${{ github.event_name }}"
        echo "Build only: ${{ github.event.inputs.build_only }}"
        echo "Push to registry: ${{ github.event.inputs.push_to_registry }}"
        echo "Container: mamana/eagle-vcf-processing:eagle-2.4.1"
        echo "Tools included: Eagle 2.4.1, BCFtools 1.20, VCFtools 0.1.16, tabix"
        echo "Platform: linux/amd64"
        echo "==================================================" 